Algoritmo "exercicio1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/03/2026
Var
// Seção de Declarações das variáveis 
idade:inteiro
nome, profissao:caractere
salario, valor:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
//idade <- 25
//nome <- "Fábio"
//valor <- 4500
//salario <- valor
escreval (" Digite a sua idade")
leia (idade)
escreval (" Digite o seu nome")
leia (nome)
escreval ("Digite a sua profissão")
leia (profissao)
escreval ("Digite o seu salário")
leia (salario)


Fimalgoritmo