Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/03/2026
Var
// Seção de Declarações das variáveis 
nome_lanche: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Escreval ("Restaurante Legal")
Escreval ("Cardápio")
Escreval ("Lanches")
Escreval ("Pastel de Carne R$8,50")
Escreval ("Pastel de Frango R$8,50")
Escreval ("Coxinha de Frango R$8,00")
Escreval ("Pão de Queijo R$5,00")
Escreval ("Bebidas")
Escreval ("Coca Cola R$6,50")
Escreval ("Guaraná R$6,50")
Escreval ("Pepsi Twist R$6,50")
Escreval ("Água sem gás R$4,50")
Escreval ("Digite o seu lanche")
leia (nome_lanche)
Escreval ("Seu pedido foi realizado")


Fimalgoritmo